// Canonical seed dataset for VO2 Builder.
//
// This is the single source of truth for the 8 mockup sessions. It is consumed
// by BOTH `supabase/seed.ts` (to populate a real database) and `lib/data.ts`
// (as the in-memory fallback when Supabase env vars are absent, so the app is
// demoable out of the box). HR streams are generated by a deterministic PRNG so
// the dataset is byte-stable across runs and reloads.

import type {
  AppSettings,
  HRSamplePoint,
  HRStream,
  Session,
  SessionModalityDetail,
  VO2BuilderEvent,
} from "./types";

const NOW = "2026-07-10T09:32:00.000Z";

// --- deterministic PRNG (mulberry32) --------------------------------------
function mulberry32(seed: number) {
  return function () {
    seed |= 0;
    seed = (seed + 0x6d2b79f5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/**
 * Generate a synthetic second-by-second-ish HR stream, sampled every `step`
 * seconds, shaped by session type:
 *   - zone2:     starts ~115, gradual upward drift to ~130, mild noise
 *   - intervals: 4×4 structure — ~110 recovery / 165–185 effort blocks
 *   - benchmark: steady build from ~140 to ~175
 */
export function generateHRStream(
  sessionType: Session["session_type"],
  durationSeconds: number,
  seed: number,
  step = 5
): HRSamplePoint[] {
  const rand = mulberry32(seed);
  const points: HRSamplePoint[] = [];
  const n = Math.floor(durationSeconds / step);

  if (sessionType === "intervals") {
    // 4 work intervals of 4 min with recovery between; warm-up + cool-down.
    const workBpm = () => 168 + rand() * 17; // 168–185
    const recBpm = () => 105 + rand() * 12; // 105–117
    for (let i = 0; i <= n; i++) {
      const t = i * step;
      const mins = t / 60;
      let base: number;
      if (mins < 4)
        base = 100 + (mins / 4) * 55; // warm-up ramp
      else {
        const cyclePos = (mins - 4) % 6; // 4 min work + 2 min rest
        base = cyclePos < 4 ? workBpm() : recBpm();
      }
      const noise = (rand() - 0.5) * 4;
      points.push({ time: t, heartrate: Math.round(base + noise) });
    }
  } else if (sessionType === "benchmark") {
    for (let i = 0; i <= n; i++) {
      const t = i * step;
      const frac = i / n;
      const base = 140 + frac * 35; // 140 -> 175
      const noise = (rand() - 0.5) * 5;
      points.push({ time: t, heartrate: Math.round(base + noise) });
    }
  } else {
    // zone2
    for (let i = 0; i <= n; i++) {
      const t = i * step;
      const frac = i / n;
      const base = 115 + frac * 15; // 115 -> 130 drift
      const noise = (rand() - 0.5) * 6;
      points.push({ time: t, heartrate: Math.round(base + noise) });
    }
  }
  return points;
}

// --- ids ------------------------------------------------------------------
const id = (n: number) =>
  `00000000-0000-4000-8000-${String(n).padStart(12, "0")}`;

// --- app_settings ---------------------------------------------------------
export const SEED_SETTINGS: AppSettings = {
  id: id(900),
  max_heartrate: 192,
  updated_at: NOW,
};

// --- sessions (8, matching the mockup exactly) ----------------------------
type SeedSpec = {
  name: string;
  date: string;
  modality: Session["modality"];
  type: Session["session_type"];
  durationSeconds: number;
  avg: number;
  peak: number;
  stravaId: number;
  notes: string;
  detail: Partial<
    Omit<SessionModalityDetail, "id" | "session_id" | "created_at" | "updated_at">
  >;
};

const SPECS: SeedSpec[] = [
  {
    name: "Intervals — Rower",
    date: "2026-07-10",
    modality: "rowing",
    type: "intervals",
    durationSeconds: 1800,
    avg: 158,
    peak: 186,
    stravaId: 12000000001,
    notes:
      "Felt strong on sets 1–3. HR recovery between sets improving vs last week.",
    detail: { avg_split: "2:08" },
  },
  {
    name: "Zone 2 — Rower",
    date: "2026-07-06",
    modality: "rowing",
    type: "zone2",
    durationSeconds: 2400,
    avg: 117,
    peak: 129,
    stravaId: 12000000002,
    notes: "Kept it easy. HR stable throughout — minimal drift. Good base session.",
    detail: { avg_split: "2:28" },
  },
  {
    name: "Zone 2 — Treadmill",
    date: "2026-07-02",
    modality: "treadmill",
    type: "zone2",
    durationSeconds: 2700,
    avg: 122,
    peak: 136,
    stravaId: 12000000003,
    notes: "Incline walk. Stayed comfortably in Z2 the whole session.",
    detail: { speed_mph: 3.5, incline_pct: 8 },
  },
  {
    name: "Intervals — Rower",
    date: "2026-06-29",
    modality: "rowing",
    type: "intervals",
    durationSeconds: 1800,
    avg: 161,
    peak: 189,
    stravaId: 12000000004,
    notes: "Hard session. Peak HR touched 189 on set 3.",
    detail: { avg_split: "2:05" },
  },
  {
    name: "Zone 2 — Rower",
    date: "2026-06-25",
    modality: "rowing",
    type: "zone2",
    durationSeconds: 2100,
    avg: 119,
    peak: 131,
    stravaId: 12000000005,
    notes: "Solid. Kept split consistent and HR stayed in zone.",
    detail: { avg_split: "2:25" },
  },
  {
    name: "5K Test — Treadmill",
    date: "2026-06-22",
    modality: "treadmill",
    type: "benchmark",
    durationSeconds: 1440,
    avg: 168,
    peak: 181,
    stravaId: 12000000006,
    notes:
      "First benchmark. Baseline 5K at 1% incline, treadmill. Use for comparison.",
    detail: { speed_mph: 7.8, incline_pct: 1, avg_pace: "7:47" },
  },
  {
    name: "Intervals — Rower",
    date: "2026-06-18",
    modality: "rowing",
    type: "intervals",
    durationSeconds: 1680,
    avg: 158,
    peak: 185,
    stravaId: 12000000007,
    notes: "4×4 on the erg. Consistent splits across all four sets.",
    detail: { avg_split: "2:07" },
  },
  {
    name: "Zone 2 — Rower",
    date: "2026-06-15",
    modality: "rowing",
    type: "zone2",
    durationSeconds: 2100,
    avg: 121,
    peak: 133,
    stravaId: 12000000008,
    notes: "Base session. Slight upward drift in the last 10 minutes.",
    detail: { avg_split: "2:26" },
  },
];

export const SEED_SESSIONS: Session[] = SPECS.map((s, i) => ({
  id: id(i + 1),
  strava_activity_id: s.stravaId,
  name: s.name,
  session_date: s.date,
  modality: s.modality,
  session_type: s.type,
  duration_seconds: s.durationSeconds,
  avg_heartrate: s.avg,
  max_heartrate: s.peak,
  notes: s.notes,
  strava_synced_at: `${s.date}T09:30:00.000Z`,
  deleted_at: null,
  created_at: `${s.date}T09:30:00.000Z`,
  updated_at: `${s.date}T09:30:00.000Z`,
}));

export const SEED_DETAILS: SessionModalityDetail[] = SPECS.map((s, i) => ({
  id: id(i + 100),
  session_id: id(i + 1),
  speed_mph: s.detail.speed_mph ?? null,
  incline_pct: s.detail.incline_pct ?? null,
  avg_split: s.detail.avg_split ?? null,
  avg_power_watts: s.detail.avg_power_watts ?? null,
  avg_cadence_rpm: s.detail.avg_cadence_rpm ?? null,
  avg_pace: s.detail.avg_pace ?? null,
  route_notes: s.detail.route_notes ?? null,
  created_at: `${s.date}T09:30:00.000Z`,
  updated_at: `${s.date}T09:30:00.000Z`,
}));

export const SEED_STREAMS: HRStream[] = SPECS.map((s, i) => {
  const data = generateHRStream(s.type, s.durationSeconds, i + 1);
  return {
    id: id(i + 200),
    session_id: id(i + 1),
    data,
    resolution: "high",
    original_size: s.durationSeconds,
    created_at: `${s.date}T09:31:00.000Z`,
  };
});

export const SEED_EVENTS: VO2BuilderEvent[] = SPECS.flatMap((s, i) => {
  const base: VO2BuilderEvent = {
    id: id(i + 300),
    session_id: id(i + 1),
    event_type: "session_created",
    payload: {
      name: s.name,
      strava_activity_id: s.stravaId,
      session_type: s.type,
    },
    created_at: `${s.date}T09:30:30.000Z`,
  };
  const streamEvent: VO2BuilderEvent = {
    id: id(i + 400),
    session_id: id(i + 1),
    event_type: "hr_stream_attached",
    payload: { data_points: s.durationSeconds, resolution: "high" },
    created_at: `${s.date}T09:31:00.000Z`,
  };
  return [base, streamEvent];
});
